# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sme-agent',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/sme-agent',
                'lib_path': 'sme_agent'},
  'syms': {'sme_agent.core': {'sme_agent.core.foo': ('core.html#foo', 'sme_agent/core.py')}}}
